### ISSUE TITLE
没有找到c# SDK的XA模式

### ISSUE THREAD

**Issue by zivfuture** [dtm-labs/dtmcli-csharp#43]
我在demo/src中都没有发现关于 XA模式的事务支持， 请问是我看漏了，还是c#的SDK里暂未支持XA模式？

**Comment by catcherwong** [comment]
@zivfuture  目前没有支持 XA模式。

如果你感兴趣的话，欢迎 PR 。

**Comment by zivfuture** [comment]
@catcherwong   感谢反馈， 我再深入了解一下，可以的话我来PR

**Comment by yedf2** [comment]
@zivfuture 非常欢迎，如果遇见xa本身的任何问题，我这可以解答。您可以加我微信yedf2008，备注csharp，微信上面可以很及时回复您
