### ISSUE TITLE
希望sdk能基于.netstandard2.0

### ISSUE THREAD

**Issue by zaki-zhao** [dtm-labs/dtmcli-csharp#44]
当前sdk基于netstandard2.1导致.net FX项目无法使用。
![image](https://user-images.githubusercontent.com/100392724/173285669-68213f62-c9bc-4976-a589-33c0e675810f.png)
个人建议将sdk包的.netstandard版本由2.1调整至2.0（版本调整会增加sdk包代码量和实现难度）。好处如下：
1、更好的在.net生态圈推广，让传统行业的.net FX开发人员便捷使用分布式事务
2、帮助.net版本升级的公司。减少从.net FX向.net core3.1+版本升级的过程中分布式事务相关的弯路
3、更便捷的在.net 和java技术栈共存的公司中推广

**Comment by catcherwong** [comment]
已经支持  netstandard2.0
